apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: node-app
  annotations:
    github.com/project-slug: rfp-vivo-2023/node-app
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: coe-tech
spec:
  type: service
  lifecycle: development
  owner: squad-1
