apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: node-app
  annotations:
    github.com/project-slug: rfp-vivo-2023/node-app
spec:
  type: other
  lifecycle: unknown
  owner: squad-1
